language: go
go:
    - 1.1
    - 1.2
    - tip
install:
    - go list -f '{{range .Imports}}{{if ne . "github.com/nickpresta/gowave/wave"}}{{.}} {{end}}{{end}}' ./... | xargs go get -v
    - go list -f '{{range .TestImports}}{{if ne . "github.com/nickpresta/gowave/wave"}}{{.}} {{end}}{{end}}' ./... | xargs go get -v
    - go build -v ./...
script:
    - go test -v -coverprofile=cover.out ./...
after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=cover.out skal80cDbbobV3oSWMYAQpnf3Bwsa2WOy
